workspace:
  base: /home/centos
  path: .

pipeline:
  test:
    image: golang:1.8
    commands:
      - echo hello world
      - cat README.md

  git_push:
    image: appleboy/drone-git-push
    branch: master
    remote: git@github.com:test_done.git
    empty_commit: true
    force: false
